### PR TITLE
Add link on travis badge

### PR DESCRIPTION
**Pull request by ewjoachim**

### CODE REVIEW

**Comment by brunobord** [comment]
Maybe you could add an entry in the changelog. or maybe not, it's a minor change that won't impact users.

**Comment by ewjoachim** [comment]
I have to admit the sole reason for this PR is actually to have the travis build and see how it goes. And as you can see...

**Comment by ewjoachim** [comment]
LGTY then ?

**Comment by brunobord** [comment]
Yup. But it's weird, the builds have failed.

**Comment by ewjoachim** [comment]
And thanks to this PR, we know :)

I'd better have a failing build written on the front page of the repo than a broken promise of a passing build

So next thing to do is to fix travis. But now we know it's broken !

**Pull request merged**
